// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB92hi0pzGfaX5_L3VlUn0_fftYQ2mDCeA',
    appId: '1:186515095138:web:a837fe90e306c387c89b3b',
    messagingSenderId: '186515095138',
    projectId: 'flexiconvert-79f5e',
    authDomain: 'flexiconvert-79f5e.firebaseapp.com',
    storageBucket: 'flexiconvert-79f5e.firebasestorage.app',
    measurementId: 'G-MPPJJ8JB95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9DX2QaZWqSR0RwrPrRl1GyEEWAQbR4A',
    appId: '1:186515095138:android:249212e504d98315c89b3b',
    messagingSenderId: '186515095138',
    projectId: 'flexiconvert-79f5e',
    storageBucket: 'flexiconvert-79f5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO: ADD YOUR API KEY HERE',
    appId: 'TODO: ADD YOUR APP ID HERE',
    messagingSenderId: 'TODO: ADD SENDER ID HERE',
    projectId: 'TODO: ADD PROJECT ID HERE',
    storageBucket: 'TODO: ADD STORAGE BUCKET HERE',
    iosBundleId: 'com.phynex.flexiconvert',
  );
}
