org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.workers.max=2
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.javaCompile.suppressSourceTargetDeprecationWarning=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.20.8-hotspot
