import 'package:permission_handler/permission_handler.dart';
import 'dart:io';
import 'package:device_info_plus/device_info_plus.dart';

class PermissionUtils {
  static Future<bool> requestStoragePermission() async {
    if (Platform.isAndroid) {
      final androidInfo = await DeviceInfoPlugin().androidInfo;
      if (androidInfo.version.sdkInt <= 29) {
        final status = await Permission.storage.request();
        return status.isGranted;
      } else {
        // Android 11+ needs manageExternalStorage to read PDFs/ZIPs generated by previous app versions in public directories
        final status = await Permission.manageExternalStorage.request();
        
        // Also request granular media permissions for good measure on Android 13+
        if (androidInfo.version.sdkInt >= 33) {
          await [
            Permission.photos,
            Permission.videos,
            Permission.audio,
          ].request();
        }
        
        return status.isGranted;
      }
    }
    
    // iOS and others
    final status = await Permission.storage.request();
    return status.isGranted;
  }
}
